-- Admin user reset: régi admin törlése és új admin hozzáadása
-- 
-- FONTOS: Ez a migráció csak akkor fut le sikeresen, ha az admin user már létezik az auth.users táblában.
-- 
-- ÚJ ADMIN USER LÉTREHOZÁSA:
-- 1. Menj a Supabase Dashboard-ba > Authentication > Add user
-- 2. Add meg az admin email címét és egy erős jelszót
-- 3. Kapcsold be az "Auto Confirm User" opciót
-- 4. Mentsd el a felhasználót
-- 5. Futtasd ezt a migrációt, amely hozzáadja a felhasználót az admin_users táblához
--
-- MEGJEGYZÉS: Az admin email és jelszó NEM szerepelhet a forráskódban biztonsági okokból!

-- Régi admin userek törlése az admin_users táblából
-- MÓDOSÍTSD AZ EMAIL DOMAIN-T AZ AKTUÁLIS DOMAIN-RE!
-- DELETE FROM public.admin_users 
-- WHERE user_id IN (
--   SELECT id FROM auth.users 
--   WHERE email LIKE '%@programlaz.hu'  -- MÓDOSÍTSD IDE AZ AKTUÁLIS DOMAIN-T!
-- );

-- Új admin user hozzáadása (csak akkor fut le, ha az auth.users táblában már létezik)
-- MÓDOSÍTSD AZ EMAIL CÍMET AZ AKTUÁLIS ADMIN EMAIL CÍMRE!
-- 
-- Példa használat:
-- INSERT INTO public.admin_users (user_id) 
-- SELECT id FROM auth.users 
-- WHERE email = 'admin@programlaz.hu'  -- MÓDOSÍTSD IDE AZ AKTUÁLIS ADMIN EMAIL CÍMET!
-- ON CONFLICT (user_id) DO NOTHING;
--
-- VAGY közvetlenül a user_id-vel:
-- INSERT INTO public.admin_users (user_id) 
-- VALUES ('<user-uuid-from-auth-users-table>')
-- ON CONFLICT (user_id) DO NOTHING;
